print("**********")
print("5 Mark Average Calculator")
print("**********\n")
print("Enter the marks in:")
a = float(input("Subject 1: "))
b = float(input("Subject 2: "))
c = float(input("Subject 3: "))
d = float(input("Subject 4: "))
e = float(input("Subject 5: "))
print("The Average Marks are: ",(a+b+c+d+e)/5)