print("**********")
print("Celsius to Fahrenheit Converter")
print("**********\n")
f = int(input("Enter amount of Fahrenheit: "))
print("The amount of Celsius is: ",(5*(f-32))/9)
print("**********")
print("Fahrenheit to Celsius Converter")
print("**********\n")
c = int(input("Enter amount of Celsius: "))
print("The amount of Fahrenheit is: ",(9/5)*c+32)